### ISSUE TITLE
Create groups

### ISSUE THREAD

**Issue by faustofjunqueira** [faustofjunqueira/keycloak-role-tool#2]
Adicionar no .yaml o tratamento de groups.

```yaml
...
groups:
    name: MyGroups
    - roles: 
        - Role1
        - Role1
        - Role1
        - Role1
        - <ClientId1>Role1
...
```
